<a href="https://colab.research.google.com/github/AkhileshGudimella/ML/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np
one_dimentional_array = np.array([1, 2, 3, 4, 5])
print(one_dimentional_array)
print(one_dimentional_array.size)
print(one_dimentional_array.ndim)
print(one_dimentional_array.shape)

[1 2 3 4 5]
5
1
(5,)


In [51]:
import numpy as np
two_dimentional_array = np.array([[1, 2, 3],[4, 5, 6]])
print(two_dimentional_array)
print(two_dimentional_array.size)
print(two_dimentional_array.ndim)
print(two_dimentional_array.shape)

[[1 2 3]
 [4 5 6]]
6
2
(2, 3)


In [52]:
import numpy as np
three_dimentional_array = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
print(three_dimentional_array)
print(three_dimentional_array.size)
print(three_dimentional_array.ndim)
print(three_dimentional_array.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12
3
(2, 2, 3)


In [13]:
import numpy as np
array_mean=np.mean([1, 2, 3, 4, 5])
print(array_mean)

3.0


In [12]:
import numpy as np
array_median=np.median([1, 2, 3, 4, 5])
print(array_median)

3.0


In [26]:
import numpy as np

n = int(input("Enter the number of elements in the array: "))
array = []
print("Enter the elements of the array, one by one:")
for i in range(n):
    element = float(input(f"Element {i+1}: "))
    array.append(element)

array_mean = np.mean(array)
print(f"The mean of the array is: {array_mean:.2f}")

Enter the number of elements in the array: 2
Enter the elements of the array, one by one:
Element 1: 1
Element 2: 2
The mean of the array is: 1.50
